# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

######################################################################

# 09/03/2014 Solution

sum = 0
fib = [1,1,0]

while fib.last < 4000000
  if fib.last % 2 == 0
    sum += fib.last
  end
  # remove ol' fib from end
  fib.pop
  # append new fib to front
  fib.unshift(fib.reduce(:+))
end

p sum